[package]
name = "four-equals-ten"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name="brute"
path="./src/brute.rs"

[dependencies]
itertools = "0.10.5"
